### ISSUE TITLE
"contents.trim is not a function" in serverless 1.44.1

### ISSUE THREAD

**Issue by ChristopheBougere** [piercus/serverless-stepfunction-validator#4]
Since I upgraded to serverless 1.44.1, I'm having this error:
```bash
npx serverless package
 
  Type Error ---------------------------------------------
 
  contents.trim is not a function
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     OS:                     darwin
     Node Version:           10.15.3
     Serverless Version:     1.44.1
 
```

Here is a reproduction code:
**serverless.yml**
```
service: my-service

provider:
  name: aws
  runtime: nodejs10.x

plugins:
- serverless-step-functions
- serverless-stepfunction-validator
```
**package.json**
```json
{
  "name": "repro-stepfunction-validator",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "dependencies": {},
  "devDependencies": {
    "serverless": "^1.44.1",
    "serverless-step-functions": "^1.21.1",
    "serverless-stepfunction-validator": "^1.3.0"
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC"
}
```
